<div id="credit-point">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Credit Points Tab</h4>
        </div>
        <div id="group_fields4" class="fieldset fieldset-wide">
            <div class="hor-scroll">
                <table class="form-list credit-table" cellspacing="0">
                    <tbody>
                        <tr>
                            <td class="label"><label for="_accountcredit_point"><?php echo $this->__('Credit Points') ?></label></td>
                            <td class="value">
                                <input type="text" class=" input-text credit-point" value="<?php echo $this->getCreditPoint() ?>" name="account[credit_point]" id="_accountcredit_point">  
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>